{% set name = "dataprep" %}
{% set version = "0.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4fa04ec5a9c6e5c549748884a17b2d9916aeb2cd31d0c3405c7c3208505efa64

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=1
  run:
    - python >=3.6
    - bokeh >=2,<3
    - bottleneck >=1.3,<2
    - dask >=2021.11,<2022
    - nltk >=3.5,<4
    - numpy >=1.21,<2
    - pandas >=1.1,<2
    - scipy >=1,<2
    - wordcloud >=1.8,<2

    # Dependencies for Connector
    - aiohttp >=3.6,<4
    - ipywidgets >=7.5,<8
    - jinja2 >=2.11,<3
    - jsonpath-ng >=1.5,<2
    - pydantic >=1.6,<2
    - tqdm >=4.48,<5

    # Dependencies for Clean
    - flask >=1.1,<2
    - flask_cors >=3,<4
    - python-levenshtein >=0.12,<0.13
    - metaphone >=0.6,<0.7
    - python-stdnum >=1.16,<2
    - regex >=2021,<2022
    - usaddress >=0.5.10,<0.6
    - varname >=0.8.1,<0.9

test:
  imports:
    - dataprep
    - dataprep.assets
    - dataprep.clean
    - dataprep.connector
    - dataprep.connector.generator
    - dataprep.connector.schema
    - dataprep.datasets
    - dataprep.eda
    - dataprep.eda.basic
    - dataprep.eda.correlation
    - dataprep.eda.create_report
    - dataprep.eda.distribution
    - dataprep.eda.missing


about:
  home: https://dataprep.ai
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Dataprep: Data Preparation in Python'
  doc_url: https://docs.dataprep.ai
  dev_url: https://github.com/sfu-db/dataprep

extra:
  recipe-maintainers:
    - dovahcrow
