{% set name = "dataprep" %}
{% set version = "0.2.13.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 813fe06e041c45e3873fecd984c686ea064d397fe07d8ea34c2bdde06c311d41

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pip
    - python
    - poetry >=1
  run:
    - aiohttp >=3.6.2,<4.0.0
    - bokeh >=2.0,<2.1
    - bottleneck >=1.3.2,<2.0.0
    - dask >=2.25,<2.26
    - cloudpickle >=0.2.2
    - distributed >=2.0
    - fsspec >=0.6.0
    - toolz >=0.8.2
    - ipython >=5.4.0
    - jinja2 >=2.11,<2.12
    - jsonpath-ng >=1.5.1,<2.0.0
    - jsonschema >=3.2,<3.3
    - lxml >=4.5,<4.6
    - nltk >=3.4.4,<4.0
    - numpy >=1.19,<1.20
    - pandas >=1.0,<1.1
    - partd >=0.3.10
    - pillow >=7.1.2,<8.0.0
    - pydantic >=1.6.1,<2.0.0
    - python
    - pyyaml
    - requests >=2.24,<2.25
    - scipy >=1.5,<1.6
    - stringcase >=1.2.0,<2.0.0
    - tornado ==5.0.2
    - tqdm >=4.48,<4.49
    - wordcloud >=1.8,<1.9

test:
  imports:
    - dataprep
    - dataprep.assets
    - dataprep.connector
    - dataprep.connector.generator
    - dataprep.connector.schema
    - dataprep.clean
    - dataprep.eda
    - dataprep.eda.basic
    - dataprep.eda.correlation
    - dataprep.eda.create_report
    - dataprep.eda.distribution
    - dataprep.eda.missing


about:
  home: https://github.com/sfu-db/dataprep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Dataprep: Data Preparation in Python'
  doc_url: https://sfu-db.github.io/dataprep/
  dev_url: https://github.com/sfu-db/dataprep

extra:
  recipe-maintainers:
    - dovahcrow
