{% set name = "dataprep" %}
{% set version = "0.4.3a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: 0f12cafb4ca7dc4e8cc89c659315dc2bba6833807500ad4a252af542143d697c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=1
  run:
    - aiohttp >=3.6,<4.0.0
    - bokeh >=2.0,<3
    - bottleneck >=1.3,<2.0
    - dask >=2021.11
    - cloudpickle >=0.2.2
    - fsspec >=0.6.0
    - toolz >=0.8.2
    - partd >=0.3.10
    - pyyaml
    - toolz >=0.8.2
    - ipywidgets >=7.5,<8.0
    - jinja2 >=3,<4.0
    - jsonpath-ng >=1.5,<2.0
    - nltk >=3.6.7,<4.0
    - numpy >=1.21,<2
    - pandas >=1.1,<2
    - pydantic >=1.6,<2.0
    - python >=3.6
    - scipy >=1,<2
    - tqdm >=4.48,<5.0
    - wordcloud >=1.8,<2.0

    - regex >=2021.8.3
    - flask >=2,<3
    - flask_cors >=3,<4
    - python-levenshtein >=0.12
    - metaphone >=0.6
    - python-crfsuite >=0.9.7
    - python-stdnum >=1.16
    - varname >=0.8.1

test:
  imports:
    - dataprep
    - dataprep.assets
    - dataprep.clean
    - dataprep.connector
    - dataprep.connector.generator
    - dataprep.connector.schema
    - dataprep.datasets
    - dataprep.eda
    - dataprep.eda.correlation
    - dataprep.eda.create_diff_report
    - dataprep.eda.create_report
    - dataprep.eda.diff
    - dataprep.eda.distribution
    - dataprep.eda.missing
    - dataprep.eda.outlier


about:
  home: https://github.com/sfu-db/dataprep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Dataprep: Data Preparation in Python'
  doc_url: https://sfu-db.github.io/dataprep/
  dev_url: https://github.com/sfu-db/dataprep

extra:
  recipe-maintainers:
    - dovahcrow
